[2024-03-01T03:17:34.739+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_analyzer.process_bse_data manual__2024-03-01T03:17:30.998613+00:00 [queued]>
[2024-03-01T03:17:34.746+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_analyzer.process_bse_data manual__2024-03-01T03:17:30.998613+00:00 [queued]>
[2024-03-01T03:17:34.746+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-01T03:17:34.765+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): process_bse_data> on 2024-03-01 03:17:30.998613+00:00
[2024-03-01T03:17:34.772+0000] {standard_task_runner.py:60} INFO - Started process 182 to run task
[2024-03-01T03:17:34.776+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_analyzer', 'process_bse_data', 'manual__2024-03-01T03:17:30.998613+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/stock-analyzer.py', '--cfg-path', '/tmp/tmpodcih60r']
[2024-03-01T03:17:34.778+0000] {standard_task_runner.py:88} INFO - Job 103: Subtask process_bse_data
[2024-03-01T03:17:34.864+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_analyzer.process_bse_data manual__2024-03-01T03:17:30.998613+00:00 [running]> on host 0a26efe0197d
[2024-03-01T03:17:35.232+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='root' AIRFLOW_CTX_DAG_ID='stock_analyzer' AIRFLOW_CTX_TASK_ID='process_bse_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T03:17:30.998613+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-01T03:17:30.998613+00:00'
[2024-03-01T03:17:35.233+0000] {logging_mixin.py:188} INFO - Reading /opt/***/data/bse_data.json for processing.
[2024-03-01T03:17:35.234+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock-analyzer.py", line 62, in process_bse_data
    process_data(input_file, output_file)
  File "/opt/airflow/dags/stock-analyzer.py", line 40, in process_data
    json_data = json.loads(f)
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not TextIOWrapper
[2024-03-01T03:17:35.240+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=stock_analyzer, task_id=process_bse_data, execution_date=20240301T031730, start_date=20240301T031734, end_date=20240301T031735
[2024-03-01T03:17:35.253+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 103 for task process_bse_data (the JSON object must be str, bytes or bytearray, not TextIOWrapper; 182)
[2024-03-01T03:17:35.288+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-01T03:17:35.304+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
