[2024-02-29T05:42:28.964+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.dag_run manual__2024-02-29T05:42:26.324526+00:00 [queued]>
[2024-02-29T05:42:28.976+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.dag_run manual__2024-02-29T05:42:26.324526+00:00 [queued]>
[2024-02-29T05:42:28.977+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-02-29T05:42:29.005+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): dag_run> on 2024-02-29 05:42:26.324526+00:00
[2024-02-29T05:42:29.016+0000] {standard_task_runner.py:60} INFO - Started process 73 to run task
[2024-02-29T05:42:29.024+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'dag_run', 'manual__2024-02-29T05:42:26.324526+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmp1_75_xk_']
[2024-02-29T05:42:29.026+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask dag_run
[2024-02-29T05:42:29.109+0000] {task_command.py:423} INFO - Running <TaskInstance: test_dag.dag_run manual__2024-02-29T05:42:26.324526+00:00 [running]> on host dd3a65e91098
[2024-02-29T05:42:29.243+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='root' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='dag_run' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T05:42:26.324526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T05:42:26.324526+00:00'
[2024-02-29T05:42:29.244+0000] {logging_mixin.py:188} INFO - This is a DAG run via Airflow.
[2024-02-29T05:42:29.245+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-02-29T05:42:29.263+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=dag_run, execution_date=20240229T054226, start_date=20240229T054228, end_date=20240229T054229
[2024-02-29T05:42:29.326+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T05:42:29.344+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
