[2024-02-29T06:07:37.567+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_data.call_api_and_save_response manual__2024-02-29T06:07:36.645032+00:00 [queued]>
[2024-02-29T06:07:37.575+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_data.call_api_and_save_response manual__2024-02-29T06:07:36.645032+00:00 [queued]>
[2024-02-29T06:07:37.576+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-02-29T06:07:37.607+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): call_api_and_save_response> on 2024-02-29 06:07:36.645032+00:00
[2024-02-29T06:07:37.620+0000] {standard_task_runner.py:60} INFO - Started process 76 to run task
[2024-02-29T06:07:37.623+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_data', 'call_api_and_save_response', 'manual__2024-02-29T06:07:36.645032+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmp6r_riygy']
[2024-02-29T06:07:37.629+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask call_api_and_save_response
[2024-02-29T06:07:37.686+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_data.call_api_and_save_response manual__2024-02-29T06:07:36.645032+00:00 [running]> on host 0a26efe0197d
[2024-02-29T06:07:37.823+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='root' AIRFLOW_CTX_DAG_ID='fetch_data' AIRFLOW_CTX_TASK_ID='call_api_and_save_response' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T06:07:36.645032+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T06:07:36.645032+00:00'
[2024-02-29T06:07:38.590+0000] {logging_mixin.py:188} INFO - API response saved successfully to /opt/***/data/bse_data.json
[2024-02-29T06:07:38.592+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-02-29T06:07:38.608+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=fetch_data, task_id=call_api_and_save_response, execution_date=20240229T060736, start_date=20240229T060737, end_date=20240229T060738
[2024-02-29T06:07:38.657+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T06:07:38.673+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
