[2024-02-29T05:44:26.363+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.dag_run manual__2024-02-29T05:44:24.863596+00:00 [queued]>
[2024-02-29T05:44:26.371+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.dag_run manual__2024-02-29T05:44:24.863596+00:00 [queued]>
[2024-02-29T05:44:26.371+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-02-29T05:44:26.393+0000] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): dag_run> on 2024-02-29 05:44:24.863596+00:00
[2024-02-29T05:44:26.400+0000] {standard_task_runner.py:60} INFO - Started process 103 to run task
[2024-02-29T05:44:26.403+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'dag_run', 'manual__2024-02-29T05:44:24.863596+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmpyvawpxzx']
[2024-02-29T05:44:26.407+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask dag_run
[2024-02-29T05:44:26.459+0000] {task_command.py:423} INFO - Running <TaskInstance: test_dag.dag_run manual__2024-02-29T05:44:24.863596+00:00 [running]> on host dd3a65e91098
[2024-02-29T05:44:26.561+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='root' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='dag_run' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T05:44:24.863596+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T05:44:24.863596+00:00'
[2024-02-29T05:44:26.565+0000] {logging_mixin.py:188} INFO - This is a DAG run via Airflow.
[2024-02-29T05:44:26.565+0000] {python.py:202} INFO - Done. Returned value was: 5
[2024-02-29T05:44:26.592+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=dag_run, execution_date=20240229T054424, start_date=20240229T054426, end_date=20240229T054426
[2024-02-29T05:44:26.621+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T05:44:26.656+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
